# Generated by Django 5.1.7 on 2025-03-15 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0004_certificates_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(default=django.utils.timezone.now, help_text='SEO-friendly description for the blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(default=django.utils.timezone.now, help_text='SEO-friendly title for the blog', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Unique URL-friendly identifier for the blog', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
