# Generated by Django 5.1.7 on 2025-03-17 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0005_blog_meta_description_blog_meta_title_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier for the category', max_length=255, unique=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier for the website', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(help_text='SEO-friendly title for the website', max_length=200)),
                ('meta_description', models.TextField(help_text='SEO-friendly description for the website')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website_images/')),
                ('service1', models.CharField(blank=True, max_length=200, null=True)),
                ('service2', models.CharField(blank=True, max_length=200, null=True)),
                ('service3', models.CharField(blank=True, max_length=200, null=True)),
                ('service4', models.CharField(blank=True, max_length=200, null=True)),
                ('service5', models.CharField(blank=True, max_length=200, null=True)),
                ('service6', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='vynzora_app.category')),
            ],
        ),
    ]
