# Generated by Django 5.1.7 on 2025-03-17 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0006_category_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='add_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
