# Generated by Django 5.1.7 on 2025-03-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0007_website_add_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='service1',
        ),
        migrations.RemoveField(
            model_name='website',
            name='service2',
        ),
        migrations.RemoveField(
            model_name='website',
            name='service3',
        ),
        migrations.RemoveField(
            model_name='website',
            name='service4',
        ),
        migrations.RemoveField(
            model_name='website',
            name='service5',
        ),
        migrations.RemoveField(
            model_name='website',
            name='service6',
        ),
        migrations.AlterField(
            model_name='website',
            name='add_description',
            field=models.TextField(verbose_name='Additional Description'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, verbose_name='Service Heading')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vynzora_app.website')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('website', 'heading'), name='unique_service_heading')],
            },
        ),
    ]
