# Generated by Django 5.1.7 on 2025-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0008_remove_website_service1_remove_website_service2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier for the website', max_length=255, null=True, unique=True),
        ),
    ]
