# Generated by Django 5.1.7 on 2025-03-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0009_alter_website_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_service_heading',
        ),
    ]
