# Generated by Django 5.1.7 on 2025-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0011_alter_website_add_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Unique URL identifier for the category', max_length=255, unique=True),
        ),
    ]
