# Generated by Django 5.1.7 on 2025-03-22 06:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('job_details', ckeditor.fields.RichTextField(max_length=20000)),
                ('posted_date', models.DateField()),
                ('end_date', models.DateField()),
                ('post_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vynzora_app.career_model')),
            ],
        ),
    ]
